2019-07-02 20:11:46,259 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-02 20:12:11,323 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-02 20:13:15,517 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-02 20:37:09,127 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-02 20:37:45,085 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-30 20:31:52,488 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-30 20:36:33,116 ERROR: Exception on /programs/edit/1 [POST] [in c:\python36\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Adam\desktop\City Tech Proj\app\routes.py", line 201, in editProgramForm
    editedProgram.degree = request.form['degree']
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 229, in __set__
    instance_dict(instance), value, None)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 831, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 853, in fire_replace_event
    self._replace_token or self._init_append_or_replace_token())
  File "c:\python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 88, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2019-07-30 21:01:43,505 ERROR: Exception on /programs/edit/4 [POST] [in c:\python36\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Adam\desktop\City Tech Proj\app\routes.py", line 201, in editProgramForm
    editedProgram.degree = request.form['degree']
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 229, in __set__
    instance_dict(instance), value, None)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 831, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 853, in fire_replace_event
    self._replace_token or self._init_append_or_replace_token())
  File "c:\python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 88, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2019-07-30 21:27:12,943 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-30 21:27:19,035 ERROR: Exception on /programs/edit/1 [POST] [in c:\python36\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Adam\desktop\City Tech Proj\app\routes.py", line 201, in editProgramForm
    editedProgram.degree = request.form['degree']
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 229, in __set__
    instance_dict(instance), value, None)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 831, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 853, in fire_replace_event
    self._replace_token or self._init_append_or_replace_token())
  File "c:\python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 88, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2019-07-30 21:28:25,618 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-30 21:28:29,139 ERROR: Exception on /programs/edit/1 [POST] [in c:\python36\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Adam\desktop\City Tech Proj\app\routes.py", line 201, in editProgramForm
    editedProgram.degree = request.form['degree']
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 229, in __set__
    instance_dict(instance), value, None)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 831, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 853, in fire_replace_event
    self._replace_token or self._init_append_or_replace_token())
  File "c:\python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 88, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2019-07-30 21:29:47,087 INFO: CreditTracker startup [in C:\Users\Adam\desktop\City Tech Proj\app\__init__.py:40]
2019-07-30 21:29:56,089 ERROR: Exception on /programs/edit/1 [POST] [in c:\python36\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python36\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python36\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\python36\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python36\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Adam\desktop\City Tech Proj\app\routes.py", line 201, in editProgramForm
    editedProgram.degree = request.form['degree']
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 229, in __set__
    instance_dict(instance), value, None)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 831, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "c:\python36\lib\site-packages\sqlalchemy\orm\attributes.py", line 853, in fire_replace_event
    self._replace_token or self._init_append_or_replace_token())
  File "c:\python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 88, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
